name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.1
  - pip=22.1.1
  - mlflow=1.26.0
  - scikit-learn=1.1.1
  - matplotlib=3.5.2
  - pillow=8.1.2
  - pip:
      - wandb==0.12.16
